### ISSUE TITLE
where to put username

### ISSUE THREAD

**Issue by amjiddader** [ArnavGuptaaa/Instagram-LikeAndComment-Bot#1]
hey thanks.

I was using an old python script to like posts.
that is not working anymore.

in your script can you please where and how to put username.
for example: username:superman & password :12345 

so how and where i have to use this in you file can you please edit file and add a line with example username password starting with #..

and how to control limit of likes and comments !!! and what is default limit.

Regards

**Comment by ArnavGuptaaa** [comment]
@amjiddader 
Enter Your username and password on line 115

```
session = InstaBot(superman, 1234)  # Enter username and password in respective positions
session.login()
session.main()
```

I have updated the comments in my code, you can check the main() function and edit the number of posts you want to like and comment per hashtag (default limit is 15 posts per hashtag).

Hope this helped you!
